######################################################################
# Automatically generated by qmake (2.01a) ? 3? 8 16:44:51 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
